-- SQL para Supabase - Actualización para Facturación Electrónica AFIP y Notas de Crédito

-- Columnas básicas de AFIP
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_cae TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_vto_cae TIMESTAMPTZ;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_pto_vta INT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_cbte_nro INT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS document_type TEXT DEFAULT 'REMITO';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS issuer_cuit TEXT;

-- Columnas para Notas de Crédito
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_nc_cae TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_nc_cbte_nro INT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS afip_nc_vto_cae TIMESTAMPTZ;

-- Columna opcional para número de orden autoincremental
ALTER TABLE sales ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;
